[package]
name = "rdns-ipv6"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
netlink-packet-route = "0.17.1"
rtnetlink = "0.13.1"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
